version: '3.8'

services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pguser
      POSTGRES_DB: pgdb
    ports:
      - 5432:5432

  rabbit:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 8001:15672
